### ISSUE TITLE
Lines of code numbers do not match

### ISSUE THREAD

**Issue by jlim9333** [ArtiomTr/jest-coverage-report-action#117]
Hi,

Lines of code that are posted via the plugin do not match the summary numbers that are produced via jest json-summary and the number seen in the terminal.

 

![Screen Shot 2021-07-17 at 1 39 05 pm](https://user-images.githubusercontent.com/85653304/126024389-1ecbf003-2068-4cf6-83b4-6f6885f98728.png)
![Screen Shot 2021-07-17 at 1 39 24 pm](https://user-images.githubusercontent.com/85653304/126024390-389a65fd-dcf5-4b84-a6e8-b1d726e23f04.png)

Edit: it occurs to me that the intention might be that these reporters might be different.
Please ignore this if that is the case.

**Comment by ArtiomTr** [comment]
Hello @jlim9333,

Thank you for your patience! Yes, the line coverage could not match because this action uses the `json` reporter to collect information about code coverage. However, the `json` reporter does not provide any information about line coverage - only about covered statements, branches and functions. Thus, line coverage is approximate, this action attempts to "guess" line coverage using information about covered statements. 

Hopefully this inaccuracy won't bother you too much when using this action. I'll close this issue, but if you have any ideas on how to fix it, feel free to continue the discussion!

**Comment by jlim9333** [comment]
It might be worth adding a not to the readme that it's an approx estimation.

I made a pr to use the Istanbul Line coverage calculation so it matches.

I'm not sure if my test and test assets follow your coding practices but it's there to demonstrate the differences in the snapshot.
