### ISSUE TITLE
Not running the test if the coverage file already exists?

### ISSUE THREAD

**Issue by rlejeune** [ArtiomTr/jest-coverage-report-action#20]
Nice action you got there, but I was wondering if it would be possible to add an option to not run the test if I know I ran them earlier and that the coverages files are already present. 

An easy way to make my CI faster :)

Thanks!

**Comment by ArtiomTr** [comment]
Hello!

As I understood, you want to see something like cache on this action. As I know, jest already has a cache, but you need some additional configuration to enable it in your action. Here is the [docs](https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows) for caching dependencies. If you run your action on a linux machine, the jest cache will be located under `/tmp/jest_rs`.

However, as it seems to me, the most time-consuming part - installing dependencies. Currently, this action forcibly removes `node_modules` folder, so configuring cache will not help here. I think I could add the `skip_deps_installation` option for this action, so you could use some other action for dependency installation with cache, like [bahmutov/npm-install@v1](https://github.com/bahmutov/npm-install).

What do you think? Is this solution right for you? Or is the `skip_deps_install` option not necessary in your case?

**Comment by rlejeune** [comment]
Morning!

Maybe I was not clear, sorry bout that. Actually I have a job that does 3 things, first it runs unit tests, then it does report the unit tests results to the PR and third it does report the coverage (your action here) 

So when I do run the unit tests before reporting resultsts, I already have the coverages files generated, so when your  action runs it does runs the tests again and I am tring to make my action runs faster, which is why I wanted an option to not rerun the tests when I know that the coverage results are already generated. 

Does this make sense?

**Comment by ArtiomTr** [comment]
https://github.com/ArtiomTr/jest-coverage-report-action/issues/20#issuecomment-809337361

> Does this make sense?

Yeah, now I understand what you want to see. 

#### Short answer
Currently there is no workaround for this.

#### Long answer
This action uses two coverage reporters: `text` and `text-summary`. These coverage reporters are printing output to stdin. This means, that you actually could do something like `jest . > cov.txt` and then specify as test script `cat cov.txt`, but it's not good solution, because anyway, this action will run `npm install` command.

There are two possible ways to achieve this functionality:
1. Create `skip_install` option. Not really good solution, because you still will need to specify junky commands (`jest . > cov.txt` / `cat cov.txt`)
2. Create custom coverage reporter. I think this solution is the best, because it will solve this issue and #10, because it could extract more information, required for that issue.

Hope you find this answer helpful. I will not close this issue, so you will receive a notification when it is resolved.

**Comment by taschetto** [comment]
So by using #34 and `@master`, will we need to re-run jest if we already have a `report.json` file?

**Comment by ArtiomTr** [comment]
> So by using #34 and `@master`, will we need to re-run jest if we already have a `report.json` file?

For now, yes, the action will automatically restart the jest. But we are already very close to adding the ability to skip the jest launch step. We just need to add an additional option to the configuration - `skip-step` that determines which step to skip - ` install` (for npm install step #37) or `test` (both npm install and jest launch steps)

**Comment by ArtiomTr** [comment]
Finally, this problem was solved thanks to @taschetto!

For now, until version 2.0 was released, you can try it by using `@master` version with this configuration:
```yml
name: 'coverage'
on:
    pull_request:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  skip-step: all
```
