### ISSUE TITLE
Process not defined when parsing threshold config

### ISSUE THREAD

**Issue by undsoft** [ArtiomTr/jest-coverage-report-action#248]
### Describe a bug

My `jest.config.js` looks like this:

```js
const { pathsToModuleNameMapper } = require('ts-jest/utils');
const { compilerOptions } = require('./tsconfig');

require('jest-preset-angular/ngcc-jest-processor');

// Deliberately set to not UTC.
process.env.TZ = 'Europe/Kiev';

module.exports = {
  preset: 'jest-preset-angular',
  ...
};
```

When I add `jest-coverage-report-action` to my workflow, I get
```
Warning:  Failed to parse jest configuration. "coverageThreshold" from config file will be ignored. evalmachine.<anonymous>:7
process.env.TZ = 'Europe/Kiev';
^
ReferenceError: process is not defined
    at evalmachine.<anonymous>:7:1
    at Script.runInContext (node:vm:139:12)
    at evaluateCjsModule (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:23:5853)
```
even though I am setting up node prior to this:
```
 - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
```
and I don't get this error in my previous test setup, so the issue is specific to parsing jest config by report action.

### Details
https://github.com/truenas/webui/pull/6505
https://github.com/truenas/webui/runs/5512126744?check_suite_focus=true

**Comment by ArtiomTr** [comment]
Hello @undsoft 👋,

To parse jest configuration, action evaluates your configuration in environment, with no node globals. You can easily avoid this issue by simply importing "process" module:

```diff
const { pathsToModuleNameMapper } = require('ts-jest/utils');
const { compilerOptions } = require('./tsconfig');
+ const process = require('node:process');

require('jest-preset-angular/ngcc-jest-processor');

// Deliberately set to not UTC.
process.env.TZ = 'Europe/Kiev';

module.exports = {
  preset: 'jest-preset-angular',
  ...
};
```

**Comment by therynamo** [comment]
@ArtiomTr - I also encountered this issue when defining custom threshold values in an external file. I'm curious what the design choice behind not using `node` globals was? The action runs inside of a `node` container - and utilizes `node` to run under the hood. Is there a benefit to using the package you've created https://github.com/ArtiomTr/cfgn over a simple `require.actual` in a `try/catch`?

**Comment by ArtiomTr** [comment]
Hey @therynamo :wave:,

The [cfgn](https://github.com/ArtiomTr/cfgn) is a small abstraction over configuration parsing. It resolves `.js`, `.mjs`, `.cjs`, `.ts` and `.json` configurations - all of these extensions should be supported by this action, because jest supports them ([link](https://github.com/facebook/jest/blob/main/packages/jest-config/src/constants.ts#L20)). `require.actual` will not evaluate configuration correctly, for several reasons:

1. Action is compiled in `commonjs` format, to support older node versions. The `es module` could not be "required" from commonjs - `import` should be used instead.
2. There is no support for importing `json` files from es modules in node, it is still [experimental](https://nodejs.org/api/esm.html#json-modules). This means that if this action will be moved to es-modules, this might cause some issues.
3. Node does not support typescript.

Plus, all logic with resolving these configurations and other stuff. So, I decided to put all this logic in a separate package to make it easier to maintain.

Also, I can't use the `jest-config` package because it couldn't be bundled. This means, that with `jest-config` package, action would need to run separate installation step before each run, what will decrease performance.

I agree that cfgn should inject node globals, and that the current behavior is a bug. I don't have much time to maintain this action, but I will try to fix this issue as soon as possible.

**Comment by therynamo** [comment]
Than you for that explanation - really helpful! I can take a look too if you have some parameters you'd like to scope the idea to.

Either way - appreciate you taking the time to respond!

**Comment by undsoft** [comment]
Thanks for your help.
