### ISSUE TITLE
Unexpected token in tests

### ISSUE THREAD

**Issue by Juanma97** [ArtiomTr/jest-coverage-report-action#26]
When I run the action, and pass the tests, I have the next:

FAIL src/app/main/shared/components/generic-selector/generic-selector-dialog/generic-selector-dialog.component.spec.ts
  ● Test suite failed to run

    SyntaxError: /github/workspace/frontend/src/app/main/shared/components/generic-selector/generic-selector-dialog/generic-selector-dialog.component.spec.ts: Missing semicolon. (15:15)

      13 |
      14 | describe('GenericSelectorDialogComponent', () => {
    > 15 |   let component: GenericSelectorDialogComponent;

Here is not neccessary a semicolon, why is a fail?, and this happens in all tests

**Comment by ArtiomTr** [comment]
It looks like action runs jest with default configuration (by default, jest is not supporting typescript files). There are two possible reasons why this is happening.

1. The first reason why this can happen is the absence of a jest configuration file. You need to add `jest.config.js` file and use [ts-jest](https://github.com/kulshekhar/ts-jest). For the most cases, this jest configuration would work:
```js
// jest.config.js
module.exports = {
  preset: 'ts-jest',
}
```
2. Another reason this problem may arise is the use of some kind of wrapper over jest (like [tsdx](https://github.com/formium/tsdx)), which provides custom "test" command. If you're not using vanilla jest to run your tests, then just specify custom test_script in your action:
```diff
name: 'coverage'
on:
    pull_request:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@v1.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
+                 test_script: npm run test:coverage
```
If you specify your custom script, don't forget to add `--coverage --coverageReporters="text" --coverageReporters="text-summary"` flags, because otherwise, this action will not be able to collect coverage.

Hope my answer will help you!
