### ISSUE TITLE
Threshold from action env don't read

### ISSUE THREAD

**Issue by isachivka** [ArtiomTr/jest-coverage-report-action#269]
The third option for this function is the threshold. Why you do not pass real value? 

https://github.com/ArtiomTr/jest-coverage-report-action/blob/main/src/stages/createReport.ts#L36

Icon is wrong because of it

**Comment by isachivka** [comment]
I do fix tomorrow

**Comment by isachivka** [comment]
https://github.com/ArtiomTr/jest-coverage-report-action/pull/270

**Comment by ArtiomTr** [comment]
Hello @isachivka :wave:,

The threshold value is not passed to that function, because it is a deprecated parameter - currently, this action extracts thresholds from the Jest configuration file. However, Jest has a bit complex structure for threshold information, not a single number. So, the `threshold` option will not fix the icon issue.

There is a separate issue for this  #235. I will close this issue as well as PR. Feel free to ping me or just discuss possible solutions to address this issue.
