### ISSUE TITLE
Feat: add debug option to see why github action is failing

### ISSUE THREAD

**Issue by ethanneff** [ArtiomTr/jest-coverage-report-action#27]
All my tests are passing, but I am still getting a failed error with this github action. Is there a way to pass a debug flag to see what is going on?

Maybe something like https://jestjs.io/docs/cli#--debug

```
=============================== Coverage summary ===============================
Statements   : 80.17% ( 1314/1639 )
Branches     : 70.6% ( 437/619 )
Functions    : 79% ( 365/462 )
Lines        : 79.08% ( 1187/1501 )
================================================================================

Test Suites: 1 skipped, 53 passed, 53 of 54 total
Tests:       6 skipped, 202 passed, 208 total
Snapshots:   4 passed, 4 total
Time:        30.707 s, estimated 55 s
Test execution failed with message: "The process '/usr/local/bin/npx' failed with exit code 1"
Error: ❌ The test suite failed. Please, check the console output for more details.
```

**Comment by ArtiomTr** [comment]
This action not requires debug option, because basically, all the errors are in the action's console. I've created more detailed error description in the report, but in your case, this will not give much information for you. To find why your action is failing, follow these instructions:
1. Open action console
![image](https://user-images.githubusercontent.com/44021713/117544875-18706200-b02c-11eb-9c87-5f8b8107b000.png)
2. Expand the failed step
![image](https://user-images.githubusercontent.com/44021713/117544904-31791300-b02c-11eb-8f53-3986cd776e81.png)
3. Find the line **where your test script is running** and read everything what is below - you'll find your error there:
![image](https://user-images.githubusercontent.com/44021713/117545007-95034080-b02c-11eb-9e57-bccba7a98fd4.png)
**IMPORTANT**: this action is running your test script twice: for the head and base branch. You need to find **FIRST** call, because error will be located there.
4. Additionally, if you can't find your error following these steps, you can use search field:
![image](https://user-images.githubusercontent.com/44021713/117545086-fe834f00-b02c-11eb-9b85-d36378a45470.png)

Hope my answer this will help you!
